@baseUrl = https://dane.biznes.gov.pl/api/ceidg/v3
@authToken = eyJraWQiOiJjZWlkZyIsImFsZyI6IkhTNTEyIn0.eyJnaXZlbl9uYW1lIjoiTWF0ZXVzeiIsInBlc2VsIjoiOTgwODEwMDUzNzUiLCJpYXQiOjE3NjUwMTg4NDAsImZhbWlseV9uYW1lIjoiS2lmbmVyIiwiY2xpZW50X2lkIjoiVVNFUi05ODA4MTAwNTM3NS1NQVRFVVNaLUtJRk5FUiJ9.3JOkfnf_R2eBb__YxpzYw1_2De-TOwcIdWrKh7nMHDYJ8SNT3d_B7E2igEL2B3JOC8VD0TdHvuHP1xs5o3wtZQ

GET {{baseUrl}}/firmy?dataod=2005-06-01&datado=2005-07-01 HTTP/1.1
Authorization: Bearer {{authToken}}